// scripts/generate-riddles.js
import { keccak256, toBytes } from 'viem'
import fs from 'fs'

const riddlesWithAnswers = [
  { q: "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?", a: "MAP" },
  { q: "The more you take, the more you leave behind. What am I?", a: "FOOTSTEPS" },
  { q: "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?", a: "ECHO" },
  { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "CANDLE" },
  { q: "What has hands but cannot clap?", a: "CLOCK" },
  { q: "What has a head and a tail but no body?", a: "COIN" },
  { q: "What can you catch but never throw?", a: "COLD" },
  { q: "What gets wetter the more it dries?", a: "TOWEL" },
  { q: "I have teeth but cannot bite. What am I?", a: "COMB" },
  { q: "What can fill a room but takes up no space?", a: "LIGHT" },
  { q: "What has one eye but cannot see?", a: "NEEDLE" },
  { q: "What can travel around the world while staying in a corner?", a: "STAMP" },
  { q: "What has a neck but no head?", a: "BOTTLE" },
  { q: "What has words but never speaks?", a: "BOOK" },
  { q: "What runs but never walks?", a: "WATER" },
  { q: "I fly without wings. I cry without eyes. What am I?", a: "CLOUD" },
  { q: "What has keys but no locks?", a: "KEYBOARD" },
  { q: "What can you break without touching it?", a: "PROMISE" },
  { q: "What has a thumb and four fingers but is not alive?", a: "GLOVE" },
  { q: "What goes up but never comes down?", a: "AGE" },
  { q: "What can be cracked, made, told, and played?", a: "JOKE" },
  { q: "I am always hungry and will die if not fed. What am I?", a: "FIRE" },
  { q: "The more you remove from me, the bigger I get. What am I?", a: "HOLE" },
  { q: "What has legs but cannot walk?", a: "TABLE" },
  { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", a: "M" },
  { q: "What is black when it's clean and white when it's dirty?", a: "CHALKBOARD" },
  { q: "What can you hold without touching it?", a: "BREATH" },
  { q: "What has a face and two hands but no arms or legs?", a: "CLOCK" },
  { q: "What building has the most stories?", a: "LIBRARY" },
  { q: "What has ears but cannot hear?", a: "CORN" },
  { q: "I shave every day but my beard stays the same. What am I?", a: "BARBER" },
  { q: "What invention lets you look right through a wall?", a: "WINDOW" },
  { q: "What has branches but no fruit, trunk, or leaves?", a: "BANK" },
  { q: "What five-letter word becomes shorter when you add two letters?", a: "SHORT" },
  { q: "What is always in front of you but cannot be seen?", a: "FUTURE" },
  { q: "What belongs to you but others use it more than you do?", a: "NAME" },
  { q: "What word is spelled incorrectly in every dictionary?", a: "WRONG" },
  { q: "I follow you all the time but you can never touch me. What am I?", a: "SHADOW" },
  { q: "What goes through cities and fields but never moves?", a: "ROAD" },
  { q: "What can you keep after giving it to someone?", a: "WORD" },
  { q: "What is full of holes but still holds water?", a: "SPONGE" },
  { q: "I am not alive but I grow. I don't have lungs but I need air. What am I?", a: "FIRE" },
  { q: "What can run but never walks, has a mouth but never talks?", a: "RIVER" },
  { q: "What begins with T, ends with T, and has T in it?", a: "TEAPOT" },
  { q: "What goes up and down but doesn't move?", a: "STAIRS" },
  { q: "What word contains 26 letters but only three syllables?", a: "ALPHABET" },
  { q: "What tastes better than it smells?", a: "TONGUE" },
  { q: "What is easy to get into but hard to get out of?", a: "TROUBLE" },
  { q: "I turn once, what is out will not get in. I turn again, what is in will not get out. What am I?", a: "KEY" },
  { q: "What kind of coat can only be put on when wet?", a: "PAINT" },
  { q: "What do you bury when it's alive and dig up when it's dead?", a: "PLANT" },
  { q: "People make me, save me, change me, and raise me. What am I?", a: "MONEY" },
  { q: "I have a head, a tail, but no legs. What am I?", a: "COIN" },
  { q: "What kind of room has no doors or windows?", a: "MUSHROOM" },
  { q: "If you drop me, I'm sure to crack. Give me a smile and I'll smile back. What am I?", a: "MIRROR" },
  { q: "What is so fragile that saying its name breaks it?", a: "SILENCE" },
  { q: "What has a ring but no finger?", a: "PHONE" },
  { q: "I am taken from a mine and shut in a wooden case. What am I?", a: "PENCIL" },
  { q: "What gets sharper the more you use it?", a: "BRAIN" },
  { q: "What has many keys but can't open a single lock?", a: "PIANO" },
  { q: "What word looks the same upside down and backwards?", a: "SWIMS" },
  { q: "What comes down but never goes up?", a: "RAIN" },
  { q: "What has an eye but cannot see?", a: "STORM" },
  { q: "What is harder to catch the faster you run?", a: "BREATH" },
  { q: "What has a bed but never sleeps?", a: "RIVER" },
  { q: "What has four fingers and a thumb but isn't alive?", a: "GLOVE" },
  { q: "What is lighter than air but impossible to lift?", a: "BUBBLE" },
  { q: "What is at the end of a rainbow?", a: "W" },
  { q: "What starts with E, ends with E, but only has one letter?", a: "ENVELOPE" },
  { q: "What runs around a yard without moving?", a: "FENCE" },
  { q: "What is cut on a table but never eaten?", a: "CARDS" },
  { q: "What has roots that nobody sees and grows taller than trees?", a: "MOUNTAIN" },
  { q: "What disappears the moment you say its name?", a: "SILENCE" },
  { q: "What thrives when you feed it but dies when you water it?", a: "FIRE" },
  { q: "What has 88 keys but cannot open a single door?", a: "PIANO" },
  { q: "What has a spine but no bones?", a: "BOOK" },
  { q: "What can be swallowed, but can also swallow you?", a: "PRIDE" },
  { q: "What becomes smaller when you turn it upside down?", a: "NINE" },
  { q: "Forward I am heavy, backward I am not. What am I?", a: "TON" },
  { q: "What kind of tree can you carry in your hand?", a: "PALM" },
  { q: "I can be long or short. I can be grown or bought. What am I?", a: "HAIR" },
  { q: "What has a bark but no bite?", a: "TREE" },
  { q: "What gets broken without being held?", a: "PROMISE" },
  { q: "I am a seed with three letters in my name. Take away two and I sound the same. What am I?", a: "PEA" },
  { q: "What goes from Z to A?", a: "ZEBRA" },
  { q: "What wears a cap but has no head?", a: "BOTTLE" },
  { q: "What do you answer even though it never asks you a question?", a: "PHONE" },
  { q: "What word of five letters has one left when two letters are removed?", a: "STONE" },
  { q: "What is deaf, dumb, and blind but always tells the truth?", a: "MIRROR" },
  { q: "I am an odd number. Take away a letter and I become even. What am I?", a: "SEVEN" },
  { q: "What has a bottom at the top?", a: "LEGS" },
  { q: "What can be seen but never touched?", a: "SHADOW" },
  { q: "What has wheels and flies but is not an aircraft?", a: "GARBAGE" },
  { q: "What loses its head in the morning and gets it back at night?", a: "PILLOW" },
  { q: "What is bought by the yard and worn by the foot?", a: "CARPET" },
  { q: "What has a head, a tail, is brown, and has no legs?", a: "PENNY" },
  { q: "What can honk without a horn?", a: "GOOSE" },
  { q: "What has cities, but no houses; forests, but no trees; and water, but no fish?", a: "MAP" },
  { q: "What falls but never breaks, and breaks but never falls?", a: "DAY" },
  { q: "What can go up a chimney down but can't go down a chimney up?", a: "UMBRELLA" },
];

const riddles = riddlesWithAnswers.map(r => ({
  question: r.q,
  answerHash: keccak256(toBytes(r.a))
}))

fs.writeFileSync('riddles.json', JSON.stringify(riddles, null, 2))
console.log(`✓ Generated ${riddles.length} riddles`)
